#!/bin/bash

# Submit jobs to align pairs of overlapping projects
#
# Call:
#       ./submit-align-overlapping-projects-pair-jobs <file-list> <chunk-size>

n=`wc -l < ${1}`
mod=${2:-100}

step=$(($mod/2))
first=0
last=$(($n-1))

pwd=`pwd`
mkdir -p $pwd/jobs/log
cd $pwd/jobs/log

for i in `seq $first $step $(($last-$step))` 
do
	range="$i-$(($i+3*$step-1))"
        echo ${range}
	#qsub -cwd -pe batch 1 $pwd/jobs/align-overlapping-projects-pair-$range
	bsub -qparallel -o$pwd/jobs/log/align-overlapping-projects-pair-${range}_job%J.log -W168:00 -B -N -n6 -R"span[ptile=6]" -R"rusage[mem=3072]" $pwd/jobs/align-overlapping-projects-pair-$range
	echo "bsub -qparallel -o$pwd/jobs/log/align-overlapping-projects-pair-${range}_job%J.log -W168:00 -B -N -n6 -R"span[ptile=6]" -R"rusage[mem=3072]" $pwd/jobs/align-overlapping-projects-pair-$range"
done

cd $pwd
