#!/bin/bash

pwd=`pwd`
mkdir -p $pwd/jobs/log
cd $pwd/jobs/log

bsub -qparallel -o$pwd/jobs/log/test-projects_job%J.log -W168:00 -B -N -n6 -R"span[ptile=6]" -R"rusage[mem=3072]" -R"select[groups]" $pwd/jobs/test-projects

cd $pwd
