#!/bin/bash

ranges=`ls | grep ^[0-9][0-9]\*-[0-9][0-9]\*\$ | sort -g`

pwd=`pwd`
mkdir -p $pwd/jobs/log
cd $pwd/jobs/log

for range in $ranges
do
	#qsub -cwd -pe batch 4 $pwd/jobs/align-$range
        echo $range
	bsub -qparallel -o$pwd/jobs/log/align-${range}_job%J.log -W168:00 -B -N -n6 -R"span[ptile=6]" -R"rusage[mem=3072]" $pwd/jobs/align-$range
	echo "bsub -qparallel -o$pwd/jobs/log/align-${range}_job%J.log -W168:00 -B -N -n6 -R"span[ptile=6]" -R"rusage[mem=3072]" $pwd/jobs/align-${range}"
done

cd $pwd
